name: Terraform Destroy

env:
  AWS_REGION: eu-west-2
  AWS_ROLE_ARN: arn:aws:iam::436549840164:role/github_action_role
  AWS_BACKEND_BUCKET: aws-demo-game-terraform-state
  TF_VERSION: "1.5.0"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (e.g., dev)'
        required: true
        default: 'dev'
      confirmation:
        description: 'Type "DESTROY" to confirm deletion of all resources'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation == 'DESTROY' && github.event.inputs.environment == 'dev'
    defaults:
      run:
        working-directory: ./infra
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.AWS_BACKEND_BUCKET }}"
        env:
          AWS_BUCKET_NAME: ${{ env.AWS_BACKEND_BUCKET }}

        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
